openapi: 3.1.0
info:
  title: Ganaseguros REST API
  description: |
    Esta API REST permite el registro de documentos en SAP para el CORE de Ganaseguros.
  version: 0.1.0
tags:
  - name: General
  - name: Auth
paths:
    /Auth/ObtenerToken:
        post:
            summary: Obtiene el token de autenticación
            descirption: |-
                Para realizar el consumo de los diferentes servicios de integración, se le proporcionará un usuario con el cual podrá obtener el token, la cual permitirá al sistema integrado consumir los servicios.
            tags:
                - Auth
            operationId: obtener-token
            requestBody:
                content:
                    application/json:
                        example:
                            Username: Ganaseguros
                            Password: 123
                        schema:
                            properties:
                                Username:
                                    description: Nombre de usuario
                                    type: string
                                Password:
                                    description: Contraseña de usuario
                                    type: string
                            required:
                                - Username
                                - Password
                            type: object
            responses:
                "200":
                    description: "OK"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/actions-billing-usage"
schemas:
    actions-billing-usage:
        properties:
            included_minutes:
                description: The amount of free GitHub Actions minutes available.
                type: integer
            minutes_used_breakdown:
                properties:
                    MACOS:
                        description: Total minutes used on macOS runner machines.
                        type: integer
                    UBUNTU:
                        description: Total minutes used on Ubuntu runner machines.
                        type: integer
                    WINDOWS:
                        description: Total minutes used on Windows runner machines.
                        type: integer
                type: object
            total_minutes_used:
                description: The sum of the free and paid GitHub Actions minutes used.
                type: integer
            total_paid_minutes_used:
                description: The total paid GitHub Actions minutes used.
                type: integer
        required:
            - total_minutes_used
            - total_paid_minutes_used
            - included_minutes
            - minutes_used_breakdown
        type: object
